// Auto-import journal data to Firebase
// Run this from the browser console on tracuu.html

var IMPORT_DATA = [
// ═══ TRIẾT HỌC - CHÍNH TRỊ HỌC - XÃ HỘI HỌC ═══
{n:"TC khoa học VN và quốc tế (WoS: SCI, SCIE, SSCI, A&HCI, ESCI; Scopus)",i:"",t:"Tạp chí",p:"WoS, Scopus",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 3.0"},
{n:"TC khoa học quốc tế khác (không WoS/Scopus) - Online",i:"",t:"Tạp chí",p:"Do HĐGS liên ngành quyết định",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Báo cáo KH tại HNKH quốc tế viết bằng tiếng Anh",i:"",t:"Kỷ yếu",p:"Proceedings, có phản biện, có ISBN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Báo cáo KH tại HNKH quốc gia",i:"",t:"Kỷ yếu",p:"Proceedings, có phản biện, có ISBN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Châu Mỹ ngày nay",i:"2354-0745",t:"Tạp chí",p:"Viện Nghiên cứu Châu Mỹ, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Chính sách và Quản lý Khoa học và Công nghệ",i:"1859-3801",t:"Tạp chí",p:"Viện CL và Chính sách KH&CN, Bộ KH&CN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Chủ nghĩa xã hội – Lý luận và thực tiễn",i:"2615-9473",t:"Tạp chí",p:"Viện CNXHKH, HV Chính trị QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Cộng sản",i:"2734-9063",t:"Tạp chí",p:"Trung ương Đảng Cộng sản VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Công tác Tôn giáo",i:"1859-1760",t:"Tạp chí",p:"Ban Tôn giáo Chính phủ",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Dân chủ & Pháp luật",i:"9866-7535",t:"Tạp chí",p:"Bộ Tư pháp",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Dân tộc học",i:"0866-7632",t:"Tạp chí",p:"Viện Dân tộc học, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Đối ngoại",i:"1859-2899",t:"Tạp chí",p:"Ban Đối ngoại Trung ương",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Giáo dục",i:"2354-0753-V",t:"Tạp chí",p:"Bộ Giáo dục và Đào tạo",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Giáo dục lý luận",i:"0868-3492",t:"Tạp chí",p:"HV Chính trị Khu vực I, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Giáo dục Lý luận Chính trị quân sự",i:"1859-056x",t:"Tạp chí",p:"Học viện Chính trị, Bộ Quốc phòng",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH: Nghiên cứu Chính sách và Quản lý",i:"2615-9295",t:"Tạp chí",p:"Đại học Quốc gia Hà Nội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH: Nghiên cứu Giáo dục",i:"2615-9325",t:"Tạp chí",p:"Đại học Quốc gia Hà Nội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Khoa học (ĐH Mở TP HCM)",i:"p-2734-9349",t:"Tạp chí",p:"Trường Đại học Mở TP HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"HCM City Open University Journal of Science-Social Sciences",i:"2734-9357-E",t:"Tạp chí",p:"Trường Đại học Mở TP HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Khoa học (ĐH Sài Gòn)",i:"1859-3208",t:"Tạp chí",p:"Trường Đại học Sài Gòn",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.50"},
{n:"Khoa học (ĐH Văn Lang)",i:"2525-2429",t:"Tạp chí",p:"Trường Đại học Văn Lang",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Khoa học Chính trị",i:"1859-0187",t:"Tạp chí",p:"HV Chính trị QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Khoa học Đại học Đà Lạt",i:"0866-787X",t:"Tạp chí",p:"Trường Đại học Đà Lạt",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH ĐH Huế: Khoa học xã hội và nhân văn",i:"2588-1213",t:"Tạp chí",p:"Đại học Huế",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Khoa học Giáo dục Việt Nam",i:"2615-8957-V",t:"Tạp chí",p:"Viện Khoa học Giáo dục VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH Học viện Phụ nữ Việt Nam",i:"2615-9007",t:"Tạp chí",p:"Học viện Phụ nữ Việt Nam",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH Nội vụ (Nhập với Tổ chức Quản lý nhà nước)",i:"2354-1113",t:"Tạp chí",p:"Trường ĐH Nội vụ Hà Nội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"KH Quốc tế AGU (bao gồm cả Khoa học)",i:"0866-8086",t:"Tạp chí",p:"ĐH An Giang, ĐHQG TP HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"KH và Công nghệ (ĐH Đà Nẵng)",i:"1859-1531",t:"Tạp chí",p:"Đại học Đà Nẵng",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH và CN Việt Nam-Bản B",i:"1859-4794",t:"Tạp chí",p:"Bộ Khoa học và Công nghệ",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH Xã hội Thành phố Hồ Chí Minh",i:"1859-0136",t:"Tạp chí",p:"Viện KHXH vùng Nam Bộ, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"KH Xã hội miền Trung",i:"1859-2635",t:"Tạp chí",p:"Viện KHXH vùng Trung Bộ, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"KH Xã hội Tây Nguyên",i:"1859-4042",t:"Tạp chí",p:"Viện KHXH vùng Tây Nguyên, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"KH Xã hội và Nhân văn (ĐHQG HN)",i:"2354-1172",t:"Tạp chí",p:"Trường ĐH KHXH&NV, ĐHQG Hà Nội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"KH Xã hội Việt Nam / Vietnam Social Sciences",i:"1605-2811-V",t:"Tạp chí",p:"Viện Hàn lâm KHXH Việt Nam",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"KH XH, Nhân văn và Giáo dục (ĐH Sư phạm Đà Nẵng)",i:"1859-4603",t:"Tạp chí",p:"Trường ĐH Sư phạm, ĐH Đà Nẵng",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"KH: Khoa học Xã hội (ĐH Sư phạm HN)",i:"2354-1067",t:"Tạp chí",p:"Trường ĐH Sư phạm Hà Nội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"KH: KH Xã hội và Nhân văn (ĐH SP TP HCM)",i:"1859-3100",t:"Tạp chí",p:"Trường ĐH Sư phạm TP HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Lao động và Công đoàn",i:"0866-7578",t:"Tạp chí",p:"Tổng Liên đoàn Lao động VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Lịch sử Đảng",i:"p-2815-6382",t:"Tạp chí",p:"Viện Lịch sử Đảng, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Lịch sử quân sự",i:"2588-1310",t:"Tạp chí",p:"Viện Lịch sử quân sự, Bộ Quốc phòng",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Lý luận chính trị (kể cả Nghiên cứu lý luận)",i:"p-2525-2585",t:"Tạp chí",p:"HV Chính trị QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Lý luận chính trị Công an nhân dân",i:"2354-1393",t:"Tạp chí",p:"HV Chính trị Công an nhân dân",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Lý luận chính trị và Truyền thông",i:"1859-1485",t:"Tạp chí",p:"HV Báo chí và Tuyên truyền, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Địa lý nhân văn",i:"2354-0648",t:"Tạp chí",p:"Viện Địa lý nhân văn, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Nghiên cứu Ấn Độ và Châu Á",i:"0886-7314",t:"Tạp chí",p:"Viện NC Ấn Độ và Tây Nam Á, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Nghiên cứu Châu Âu",i:"0868-3581",t:"Tạp chí",p:"Viện NC Châu Âu, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Châu Phi và Trung Đông",i:"1859-0519",t:"Tạp chí",p:"Viện NC Châu Phi và Trung Đông, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Nghiên cứu Con người",i:"0328-1557",t:"Tạp chí",p:"Viện NC Con người, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Nghiên cứu dân tộc",i:"0886-773X",t:"Tạp chí",p:"Học viện Dân tộc",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Đông Bắc Á",i:"2354-077X",t:"Tạp chí",p:"Viện NC Đông Bắc Á, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Nghiên cứu Đông Nam Á",i:"0868-2739",t:"Tạp chí",p:"Viện NC Đông Nam Á, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Gia đình và Giới",i:"1859-1361-V",t:"Tạp chí",p:"Viện NC Gia đình và Giới, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Hồ Chí Minh",i:"2525-2550",t:"Tạp chí",p:"Viện HCM và các lãnh tụ, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Lịch sử",i:"0866-7497",t:"Tạp chí",p:"Viện Sử học, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Nghiên cứu Quốc tế",i:"1859-0608",t:"Tạp chí",p:"Học viện Ngoại giao",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Tôn giáo",i:"1859-0403",t:"Tạp chí",p:"Viện NC Tôn giáo, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu Trung Quốc",i:"0868-3670",t:"Tạp chí",p:"Viện NC Trung Quốc, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu văn hóa Việt Nam",i:"3030-4121",t:"Tạp chí",p:"Viện NC Văn hóa, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Nhà nước và Pháp luật",i:"1021-0547",t:"Tạp chí",p:"Viện Nhà nước và Pháp luật, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Nhân lực khoa học xã hội",i:"0866-756X",t:"Tạp chí",p:"HV KHXH, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Những vấn đề Kinh tế và Chính trị thế giới",i:"0868-2984",t:"Tạp chí",p:"Viện KT và CT thế giới, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nội chính",i:"0866-7934",t:"Tạp chí",p:"Ban Nội chính Trung ương",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Phát triển bền vững vùng",i:"2354-0729",t:"Tạp chí",p:"Viện NC phát triển bền vững vùng, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Phát triển Nhân lực",i:"1859-2732",t:"Tạp chí",p:"Học viện Cán bộ TP HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Quan hệ Quốc phòng",i:"1859-3739",t:"Tạp chí",p:"Viện Quan hệ quốc tế về quốc phòng, Bộ QP",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Quản lý nhà nước - State Management Review",i:"2354-0761",t:"Tạp chí",p:"Học viện Hành chính Quốc gia",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Quốc phòng toàn dân",i:"0866-7527",t:"Tạp chí",p:"Tổng cục Chính trị Quân đội nhân dân VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.50"},
{n:"Sinh hoạt lý luận",i:"0868-3247",t:"Tạp chí",p:"HV Chính trị Khu vực III, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Thông tin Khoa học Chính trị",i:"2354-1474",t:"Tạp chí",p:"HV Chính trị Khu vực IV, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Thông tin KH lý luận chính trị",i:"2354-1040",t:"Tạp chí",p:"HV Chính trị QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Thông tin Khoa học xã hội",i:"0866-8647",t:"Tạp chí",p:"Viện Thông tin KHXH, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Tổ chức nhà nước",i:"2588-137X",t:"Tạp chí",p:"Bộ Nội vụ",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Triết học (tiếng Việt và tiếng Anh)",i:"1011-9833",t:"Tạp chí",p:"Viện Triết học, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Tuyên giáo",i:"1859-2295",t:"Tạp chí",p:"Ban Tuyên giáo Trung ương",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Văn hóa nghệ thuật",i:"0866-8655",t:"Tạp chí",p:"Bộ Văn hóa, Thể thao và Du lịch",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.50"},
{n:"Xã hội học Việt Nam",i:"2615-9163",t:"Tạp chí",p:"Viện Xã hội học, Viện HL KHXH VN",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Xây dựng Đảng",i:"1859-0829",t:"Tạp chí",p:"Ban Tổ chức Trung ương",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Thanh niên",i:"2734-9039",t:"Tạp chí",p:"Trung ương Đoàn Thanh niên CS HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nguồn nhân lực và sinh xã hội",i:"2815-5610",t:"Tạp chí",p:"Trường ĐH Lao động Xã hội",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Chính trị và Phát triển",i:"1859-2457",t:"Tạp chí",p:"NXB Chính trị QG Sự thật",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Khoa học (ĐH Tân Trào)",i:"2354-1431",t:"Tạp chí",p:"Trường Đại học Tân Trào",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"KH&CN Việt Nam (Bản D) / VMOST Journal",i:"2734-9748",t:"Tạp chí",p:"Bộ Khoa học và Công nghệ",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.75"},
{n:"Nghiên cứu khoa học (ĐH Sao Đỏ)",i:"1859-4190",t:"Tạp chí",p:"Trường Đại học Sao Đỏ",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.25"},
{n:"Nghiên cứu Triết học",i:"2734-990X",t:"Tạp chí",p:"Hội Triết học",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 1.0"},
{n:"Lãnh đạo và Chính sách",i:"2815-6498",t:"Tạp chí",p:"Viện Lãnh đạo học và Hành chính công, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Nghiên cứu Văn hóa và Phát triển",i:"1815-5963",t:"Tạp chí",p:"Viện Văn hóa và Phát triển, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},
{n:"Triết học và Đời sống",i:"2734-9470",t:"Tạp chí",p:"Viện Triết học, HV CT QG HCM",f:"Triết học - Xã hội học - Chính trị học",s:"0 – 0.5"},

// ═══ VĂN HÓA - NGHỆ THUẬT - THỂ DỤC THỂ THAO ═══
{n:"TC khoa học VN và quốc tế (SCI, SCIE, SSCI, A&HCI, IF≥2.0)",i:"",t:"Tạp chí",p:"SCI, SCIE, SSCI, A&HCI",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 3.0"},
{n:"TC khoa học VN và quốc tế (SCI, SCIE, SSCI, A&HCI, IF<2.0)",i:"",t:"Tạp chí",p:"SCI, SCIE, SSCI, A&HCI",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 2.0"},
{n:"TC khoa học VN và quốc tế (ISI, Scopus)",i:"",t:"Tạp chí",p:"ISI, Scopus",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.5"},
{n:"TC Top 500 đại học hàng đầu TG theo THE",i:"",t:"Tạp chí",p:"Times Higher Education",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.25"},
{n:"Các TC quốc tế khác - Online",i:"",t:"Tạp chí",p:"Do HĐGS liên ngành quyết định",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Báo cáo KH tại HNKH quốc tế",i:"",t:"Kỷ yếu",p:"Proceedings, có phản biện, có ISBN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Báo cáo KH tại HNKH quốc gia",i:"",t:"Kỷ yếu",p:"Proceedings, có phản biện, có ISBN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Bảo tàng và nhân học",i:"0866-7616",t:"Tạp chí",p:"Bảo tàng Dân tộc học VN, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Châu Mỹ ngày nay",i:"2354-0745",t:"Tạp chí",p:"Viện NC Châu Mỹ, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Cộng sản",i:"2734-9063",t:"Tạp chí",p:"Trung ương Đảng Cộng sản VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Giáo dục và Xã hội",i:"1859-3917",t:"Tạp chí",p:"Hiệp hội các trường ĐH, CĐ VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH và Công nghệ Việt Nam (Bản B)",i:"1859-4794",t:"Tạp chí",p:"Bộ Khoa học và Công nghệ",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"KH Đại học Huế: KH xã hội và nhân văn",i:"2588-1213",t:"Tạp chí",p:"Đại học Huế",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH Đại học Huế: Kinh tế và phát triển",i:"2588-1205",t:"Tạp chí",p:"Đại học Huế",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.25"},
{n:"KH: Nghiên cứu Giáo dục (VNU J.o. Science: Education Research)",i:"2615-9325",t:"Tạp chí",p:"Đại học Quốc gia Hà Nội",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Khoa học (ĐH Sài Gòn)",i:"1859-3208",t:"Tạp chí",p:"Trường Đại học Sài Gòn",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Khoa học (ĐH Văn Hiến)",i:"1859-2961",t:"Tạp chí",p:"Trường Đại học Văn Hiến",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Khoa học (ĐH Sư phạm TP HCM)",i:"1859-3100-V",t:"Tạp chí",p:"Trường ĐH Sư phạm TP HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH xã hội miền Trung",i:"1859-2635",t:"Tạp chí",p:"Viện KHXH vùng Trung Bộ, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.25"},
{n:"KH xã hội TP Hồ Chí Minh",i:"1859-0136",t:"Tạp chí",p:"Viện KHXH vùng Nam Bộ, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH xã hội và nhân văn (ĐHQG HN)",i:"2354-1172",t:"Tạp chí",p:"Trường ĐH KHXH&NV, ĐHQG Hà Nội",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"KH Xã hội Việt Nam",i:"1013-4328",t:"Tạp chí",p:"Viện Hàn lâm KHXH Việt Nam",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Ấn Độ và Châu Á",i:"0866-7314",t:"Tạp chí",p:"Viện NC Ấn Độ và Tây Nam Á, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Châu Âu",i:"0868-3581",t:"Tạp chí",p:"Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Châu Phi và Trung Đông",i:"1859-0519",t:"Tạp chí",p:"Viện NC Châu Phi và Trung Đông, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu con người",i:"2815-5777",t:"Tạp chí",p:"Viện NC Con người, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu dân tộc",i:"0866-773X",t:"Tạp chí",p:"Học viện Dân tộc",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Đông Bắc Á",i:"2534-077X",t:"Tạp chí",p:"Viện NC Đông Bắc Á, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Đông Nam Á",i:"0868-2739",t:"Tạp chí",p:"Viện NC Đông Nam Á, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Lịch sử",i:"0866-7497",t:"Tạp chí",p:"Viện Sử học, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Trung Quốc",i:"0868-3670",t:"Tạp chí",p:"Viện NC Trung Quốc, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Phát triển KH và CN",i:"1859-0128",t:"Tạp chí",p:"ĐHQG TP HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Thông tin KH lý luận chính trị",i:"2354-1040",t:"Tạp chí",p:"HV Chính trị QG HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Thông tin Khoa học xã hội",i:"0866-8647",t:"Tạp chí",p:"Viện Thông tin KHXH, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Triết học",i:"0866-7632",t:"Tạp chí",p:"Viện Triết học, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Văn hóa học",i:"1859-4859",t:"Tạp chí",p:"Viện Văn hóa Nghệ thuật QG VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Văn hóa nghệ thuật",i:"0866-8655",t:"Tạp chí",p:"Bộ Văn hóa, Thể thao và Du lịch",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"Xã hội học Việt Nam",i:"2615-9163",t:"Tạp chí",p:"Viện Xã hội học, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Di sản văn hóa",i:"1859-4956",t:"Tạp chí",p:"Cục Di sản Văn hóa, Bộ VH-TT&DL",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Diễn đàn Văn nghệ Việt Nam",i:"0863-3093",t:"Tạp chí",p:"Hội liên hiệp Văn học nghệ thuật VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Giáo dục Âm nhạc",i:"2354-1326",t:"Tạp chí",p:"Học viện Âm nhạc QG VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Giáo dục nghệ thuật",i:"1859-4964",t:"Tạp chí",p:"Trường ĐH Sư phạm Nghệ thuật TW",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Khảo cổ học",i:"0866-742",t:"Tạp chí",p:"Viện Khảo cổ học, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH xã hội Tây Nguyên",i:"1859-4042",t:"Tạp chí",p:"Viện phát triển bền vững vùng TN, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Lý luận phê bình văn học nghệ thuật",i:"0866-7349",t:"Tạp chí",p:"Hội đồng LLPB VHNT TW",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Âm nhạc",i:"1859-4360",t:"Tạp chí",p:"Học viện Âm nhạc QG VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Mỹ thuật",i:"1859-4697",t:"Tạp chí",p:"Trường ĐH Mỹ thuật VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Sân khấu - Điện ảnh",i:"2354-0680",t:"Tạp chí",p:"Trường ĐH Sân khấu - Điện ảnh HN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Tôn giáo",i:"1859-0403",t:"Tạp chí",p:"Viện NC Tôn giáo, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu văn hóa",i:"0866-7667",t:"Tạp chí",p:"Trường Đại học Văn hóa Hà Nội",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu Văn hóa Việt Nam",i:"3030-4121",t:"Tạp chí",p:"Viện NC Văn hóa, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"Nghiên cứu văn học",i:"1859-2856",t:"Tạp chí",p:"Viện HL Khoa học Xã hội VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nhạc Việt",i:"2354-1156",t:"Tạp chí",p:"Học viện Âm nhạc Huế",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Thông tin và Tư liệu",i:"1859-2929",t:"Tạp chí",p:"Bộ Khoa học và Công nghệ",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Thư viện Việt Nam",i:"1859-1450",t:"Tạp chí",p:"Thư viện QG VN, Bộ VH-TT&DL",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Văn hóa và Nguồn lực",i:"2354-0907",t:"Tạp chí",p:"Trường ĐH Văn hóa TP HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Xưa và nay",i:"0868-331X",t:"Tạp chí",p:"Hội Khoa học Lịch sử VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nghiên cứu Văn hóa và Phát triển",i:"2815-5963",t:"Tạp chí",p:"Viện VH và PT, HV CT QG HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"KH Đại học Hạ Long",i:"2815-5521",t:"Tạp chí",p:"Trường Đại học Hạ Long",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.25"},
{n:"Mỹ thuật",i:"1859-1590",t:"Tạp chí",p:"Hội Mỹ thuật Việt Nam",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH Đại học Khánh Hòa",i:"2588-1353",t:"Tạp chí",p:"Trường Đại học Khánh Hòa",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Nguồn sáng Dân gian",i:"2525-2240",t:"Tạp chí",p:"Hội Văn nghệ Dân gian VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.25"},
{n:"KH Đào tạo và huấn luyện Thể thao",i:"1859-4417",t:"Tạp chí",p:"Trường ĐH Thể dục Thể thao Bắc Ninh",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 1.0"},
{n:"KH Thể dục Thể thao",i:"1859-4662",t:"Tạp chí",p:"Viện Khoa học Thể dục Thể thao",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
{n:"KH và đào tạo Thể dục thể thao (TP HCM)",i:"0866-8108",t:"Tạp chí",p:"Trường ĐH Thể dục thể thao TP HCM",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"KH và đào tạo thể thao (Đà Nẵng)",i:"2588-1345",t:"Tạp chí",p:"Trường ĐH Thể dục thể thao Đà Nẵng",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Sinh lý học Việt Nam",i:"1859-2376",t:"Tạp chí",p:"Hội Sinh lý học VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Tâm lý học",i:"1859-0098",t:"Tạp chí",p:"Viện Tâm lý học, Viện HL KHXH VN",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Y học thực hành",i:"1859-1663",t:"Tạp chí",p:"Bộ Y tế",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.5"},
{n:"Du lịch Việt Nam",i:"0866-7373",t:"Tạp chí",p:"Tổng cục Du lịch, Bộ VH-TT&DL",f:"Văn hoá - Nghệ thuật - TDTT",s:"0 – 0.75"},
];

console.log("Total journals to import:", IMPORT_DATA.length);
